spring.application.name=aisservice
spring.mongodb.uri=mongodb+srv://Cluster61246:xwnSDkUi6ln9HYqx@cluster61246.cv6dx6d.mongodb.net/airecommendation
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka